name: Zombi CI Actions Production (Deploy)

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    env:
      ZOMBI_ENV: ${{ secrets.PRODUCTION_SECRETS }}
    if: |
      github.ref == 'refs/heads/master' && 
      ${{ false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm i
      - name: Creates the environment file
        run: mkdir .env ; printf "%s" "$ZOMBI_ENV" > ".env/production"
      - name: Uploading code to S3
        run: |
          echo "$(date +"%Y_%m_%d.%H_%M_%S")_${ZOMBI_LAMBDA_NAME_MICROSERVER}.zip" > code_file
          . .env/development && bash ./infra/aws/iac/upload_code.sh $(cat code_file)
      - name: Deploying code for lambda MICROSERVER
        run: |
          . .env/development && bash ./infra/aws/iac/update_function.sh ${ZOMBI_LAMBDA_NAME_MICROSERVER} $(cat code_file)
      - name: Deploying code for lambda QUEUE
        run: |
          . .env/development && bash ./infra/aws/iac/update_function.sh ${ZOMBI_LAMBDA_NAME_QUEUE} $(cat code_file)
      - name: Deploying code for lambda REACTOR
        run: |
          . .env/development && bash ./infra/aws/iac/update_function.sh ${ZOMBI_LAMBDA_NAME_REACTOR} $(cat code_file)
      - name: Deploying code for lambda WEBSOCKETS
        run: |
          . .env/development && bash ./infra/aws/iac/update_function.sh ${ZOMBI_LAMBDA_NAME_WEBSOCKETS} $(cat code_file)
      - name: Deploying code for lambda FILES
        run: |
          . .env/development && bash ./infra/aws/iac/update_function.sh ${ZOMBI_LAMBDA_NAME_FILES} $(cat code_file)
      - name: Set lambdas configurations
        run: |
          . .env/development && npm run lambda:config
      - name: Run API tests
        run: . .env/development && npm run test
  error_job:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Shows error on wrong branch
        run: echo This should run only on master branch ; exit 1